# Generated by Django 4.0.4 on 2022-05-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthArea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='phone_number',
            field=models.IntegerField(default=12347890, unique=True),
            preserve_default=False,
        ),
    ]
