# Generated by Django 3.2.9 on 2022-08-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthArea', '0006_alter_usermodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('DIRECTOR', 'director'), ('SECRATARY', 'secratory'), ('OTHERS', 'others')], default='ADMIN', max_length=20),
        ),
    ]
