# Generated by Django 3.2.5 on 2022-04-19 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apprentice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apprenticeName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CollectedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCollected', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
                ('collectedFrom', models.CharField(max_length=100)),
                ('havePaid', models.BooleanField(default=False)),
                ('dateCollected', models.DateTimeField(auto_now_add=True)),
                ('datePaid', models.DateTimeField(auto_now=True)),
                ('collectedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whoPicked', to='CollectedItems.apprentice')),
            ],
        ),
    ]
