# Generated by Django 3.2.5 on 2022-04-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CollectedItems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collecteditems',
            options={'verbose_name_plural': 'Collected Items'},
        ),
    ]
