# Generated by Django 3.2.5 on 2022-04-19 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DailySales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysales',
            name='itemsold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DailySales.itemsold'),
        ),
    ]
