# Generated by Django 3.2.9 on 2022-06-24 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DailySales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='dateadded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='dateupdated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='products',
            name='restocklevel',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
