# Generated by Django 3.2.9 on 2022-06-25 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
        ('DailySales', '0002_auto_20220624_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysales',
            name='itemsold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldItem', to='Products.products'),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
