# Generated by Django 3.2.5 on 2022-04-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailySales', '0003_auto_20220419_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsold',
            name='quantity',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
