# Generated by Django 3.2.9 on 2022-08-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailySales', '0003_auto_20220625_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysales',
            name='havepaid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='paymentmethod',
            field=models.CharField(choices=[('CASH', 'cash'), ('TRANSFER', 'transfer')], default='CASH', max_length=40, null=True),
        ),
    ]
