# Generated by Django 4.0.4 on 2022-05-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DailySales', '0004_itemsold_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemSold',
            new_name='Products',
        ),
    ]
