# Generated by Django 4.0.4 on 2022-05-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailySales', '0006_alter_dailysales_datepaid_alter_dailysales_datesold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysales',
            name='datepaid',
            field=models.DateField(null=True),
        ),
    ]
