# Generated by Django 4.0.4 on 2022-05-19 10:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('DailySales', '0007_alter_dailysales_datepaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysales',
            name='datepaid',
            field=models.DateField(auto_now=True, default=datetime.datetime(2022, 5, 19, 10, 16, 57, 461176, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
