# Generated by Django 3.2.9 on 2022-08-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_products_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='total_added',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
